sh.addShard("mongo_rs1/mongo_rs1_n1:27017,mongo_rs1_n2:27017")
sh.addShard("mongo_rs2/mongo_rs2_n1:27017,mongo_rs2_n2:27017")
sh.enableSharding("bookmarks")
db.createCollection("events.all_objects")
db.createCollection("events.statistics")
sh.shardCollection("bookmarks.all_objects", {"id": "hashed"})
sh.shardCollection("bookmarks.statistics", {"id": "hashed"})