sh.addShard("mongo_rs1/mongo_rs1_n1:27017,mongo_rs1_n2:27017")
sh.addShard("mongo_rs2/mongo_rs2_n1:27017,mongo_rs2_n2:27017")
sh.enableSharding("bookmarks")
db.createCollection("events.events")
db.createCollection("events.comments")
db.createCollection("bookmarks.places")
db.createCollection("bookmarks.promotions")
sh.shardCollection("bookmarks.events", {"id": "hashed",})
sh.shardCollection("bookmarks.comments", {"id": "hashed"})
sh.shardCollection("bookmarks.places", {"id": "hashed"})
sh.shardCollection("bookmarks.promotions", {"id": "hashed"})